title: Researchly - Intelligente Patentanalyse im Handumdrehen
author: Leopold Bosankic
email: contact@leobosankic.com
description: > # this means to ignore newlines until "show_exerpts:"
  Researchly analysiert und visualisiert Patente.
  Analysieren Sie Industrien, entdecken Sie Patenttrends und
  vergleichen Sie Patentstrategien von Unternehmen.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Researchly 
  tagline: Intelligente Patentanalyse im Handumdrehen
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: true

  # generate social links in footer
  social_links:
    twitter: thelehhman
    github:  thelehhman
    linkedIn: in/thelehhman
    rss: rss